/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _proje;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean search(ArrayList<Integer> array , int i){

        System.out.println("inside search method");

        if (array ==  null)
            return false;

        for (int j = 0; j < array.size()-1; j++) {
            if(array.get(i).equals(j)) return true;
        }
            return false;
    }
}
